name: Fetch

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight (UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up the Go environment
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'

    # Step 3: Run the Go script
    - name: Run the Go Script
      run: |
        # Initialize the Go module if needed
        if [ ! -f go.mod ]; then
          go mod init ir-access
        fi

        # Tidy dependencies and run the script
        go mod tidy
        go build
        go run ir-access -f

    # Step 4: Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Ensure untracked files are added
        git add -A

        # Commit only if there are changes
        if ! git diff --cached --quiet; then
          git commit -m "Update prefixes (auto-update)"
          git push
        else
          echo "No changes detected. Skipping commit."
        fi
