name: Fetch And Commit

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight (UTC)
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'
        check-latest: true

    - name: Run the Go Script
      run: go run . -f -v

    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update prefixes (auto-update)
        file_pattern: 'ir_prefixes_v4.txt ir_prefixes_v6.txt'
